de_config:
  d_ff: 2048
  d_model: 512
  max_seq_len: 18
  n_heads: 8
  num_layer: 6
  vocab_size: 128

en_config:
  d_ff: 2048
  d_model: 512
  max_seq_len: 30
  n_heads: 8
  num_layer: 6
  vocab_size: 256

training:
  batch_size: 8
  num_epoch: 10
  lr: 1e-3

