en_config:
  d_model: 512
  d_ff: 2048
  max_seq_len: 256
  n_heads: 8
  num_layer: 6
  dropout: 0.1

de_config:
  d_model: 512
  d_ff: 2048
  max_seq_len: 64
  n_heads: 8
  num_layer: 6
  dropout: 0.1

training:
  batch_size: 64
  num_epoch: 30
  lr: 1e-4
  print_every: 200
  k: 5
